accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("", views.users, name="users"),

    path('<int:user_id>/profile/', views.profile, name='profile'),

    path('<int:user_id>/follow/', views.follow, name='follow'),

    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #첫화면은 상품리스트
    path('', include('products.urls')),
    #사용자
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class = "navbar">
        <a href="{% url 'index' %}">홈으로가기</a>
        {% if request.user.is_authenticated %}
        <p>{{ request.user.username }}님 환영합니다</p>
        <p>나의 포인트 : {{ request.user.cash }}원<a href="{% url 'accounts:cash_charge' %}">포인트 충전</a>



        </p>
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type = "submit" value = "로그아웃">
        </form>
        <a href ="{% url 'accounts:update' %}">회원정보수정</a>
        <form action="{% url 'accounts:delete' %}">
        <input type = "submit" value = "회원탈퇴">
        </form>
        {% else %}

        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
        {% endif %}
    </div>
    <div class = "container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>